apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pythonapp
  name: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pythonapp
    spec:
      containers:
      - image: rohitpatil07/myflaskapp:v1.1.5
        name: myflaskapp
        ports:
        - containerPort: 5000
        resources: {}
status: {}
