apiVersion: v1
kind: Service
metadata:
  name: python-svc
  namespace: default
  labels:
    app: pythonapp
spec:
  selector:
    app: pythonapp
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080  # Specific NodePort
  type: NodePort  # Exposes service on a specific port on each node
