apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pythonapp
  name: python-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: pythonapp
  type: NodePort
status:
  loadBalancer: {}
