apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-service
  ports:
  - name: nginx-service
    protocol: TCP
    port: 80
    targetPort: 80
#use port forwarding in this 