apiVersion: v1
kind: Service
metadata:
  name: technana-service
spec:
  selector:
    app: technana-service
  ports:
  - name: technana-service
    protocol: TCP
    port: 8080
    targetPort: 8080
#use port forwarding in this 